CC=gcc
CFLAGS=-I. -Wall

linkedlist:
	$(CC) -o linkedlist.bin LinkedList.c linkedlisttest.c -I.

queue:
	$(CC) -o queue.bin LinkedList.c Queue.c queuetest.c -I.

stack:
	$(CC) -o stack.bin LinkedList.c Stack.c stacktest.c -I.

clean:
	rm -rf *.bin
